apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inception-server-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: inception-server
    spec:
      containers:
      - name: inception-server-container
        image: rgaut/inception_serving:final
        command:
        - /bin/sh
        - -c
        args:
        - /usr/bin/tensorflow_model_server
          --port=9000 --model_name=inception --model_base_path=/models/inception
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: inception-server-service
  name: inception-server-service
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: inception-server
